# Generated by Django 4.1 on 2022-09-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variants',
        ),
    ]
