# Generated by Django 4.1 on 2022-09-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productimage'),
        ),
    ]
